# Generated by Django 5.0.2 on 2024-04-23 18:03

import django.db.models.deletion
import orders.enums.card_status
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(orders.enums.card_status.CardStatus['OPEN'], 'open'), (orders.enums.card_status.CardStatus['CANCELED'], 'canceled'), (orders.enums.card_status.CardStatus['COMPLETED'], 'completed')], default='open', max_length=10)),
                ('products', models.ManyToManyField(related_name='cards', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
